In [1]:
import pickle
import numpy
numpy.random.seed(42)
import os

In [2]:
os.chdir('..')
words_file = "text_learning/your_word_data.pkl" 
authors_file = "text_learning/your_email_authors.pkl"
word_data = pickle.load(open(words_file, "r"))
authors = pickle.load(open(authors_file, "r") )

In [32]:
def load_files():
    words_file = "text_learning/your_word_data.pkl" 
    authors_file = "text_learning/your_email_authors.pkl"
    word_data = pickle.load(open(words_file, "r"))
    authors = pickle.load(open(authors_file, "r") )
    return word_data, authors 

In [25]:
from sklearn import cross_validation
from sklearn.feature_extraction.text import TfidfVectorizer

def main():

    features_train, features_test, labels_train, labels_test = cross_validation.train_test_split(word_data, authors, 
                                                                                                 test_size=0.1, 
                                                                                                 random_state=42)

    vectorizer = TfidfVectorizer(sublinear_tf=True, max_df=0.5,
                                 stop_words='english')
    features_train = vectorizer.fit_transform(features_train)
    features_test  = vectorizer.transform(features_test).toarray()
    
    return vectorizer, features_train, features_test, labels_train, labels_test

In [5]:
features_train = features_train[:150].toarray()
labels_train   = labels_train[:150]

### How many training points are there, according to the starter code?

In [6]:
len(features_train)

150

In [29]:
from sklearn.tree import DecisionTreeClassifier

def tree():
    dtree = DecisionTreeClassifier()
    dtree = dtree.fit(features_train, labels_train)
    labels_pred = dtree.predict(features_test)
    return dtree, labels_pred

In [ ]:
dtree, labels_pred = tree()

### What’s the accuracy of the decision tree you just made?

In [11]:
from sklearn.metrics import accuracy_score
accuracy_score(labels_test, labels_pred)

0.9590443686006825

### What’s the importance of the most important feature? What is the number of this feature?

In [13]:
feature_importances = dtree.feature_importances_
numpy.argsort(feature_importances)
feature_importances[feature_importances > 0.02]

array([0.02631579, 0.07495003, 0.76470588, 0.13402829])

In [15]:
numpy.argsort(feature_importances)

array([    0, 25236, 25237, ..., 26874, 33953, 33614], dtype=int64)

In [16]:
feature_importances[33614]

0.7647058823529412

### What's the most powerful word when your decision tree is making its classification decisions?

In [20]:
print vectorizer.get_feature_names()[33614]

sshacklensf


In [26]:
word_data, authors = load_files()

In [27]:
vectorizer, features_train, features_test, labels_train, labels_test = main()

In [28]:
features_train = features_train[:150].toarray()
labels_train   = labels_train[:150]

In [30]:
dtree, labels_pred = tree()

In [31]:
feature_importances = dtree.feature_importances_
feature_importances[feature_importances > 0.2]

array([0.66666667])

In [36]:
numpy.where(feature_importances > 0.2)

(array([14343], dtype=int64),)

### Does any other highy powerful word arise after you get rid of the first "signature word"? What is the word?

In [38]:
print vectorizer.get_feature_names()[14343]

cgermannsf


### Repeat above steps and check if there's any word that contributes a feature importance > 0.2

In [39]:
word_data, authors = load_files()

In [40]:
vectorizer, features_train, features_test, labels_train, labels_test = main()

In [41]:
features_train = features_train[:150].toarray()
labels_train   = labels_train[:150]

In [42]:
dtree, labels_pred = tree()

In [43]:
feature_importances = dtree.feature_importances_
feature_importances[feature_importances > 0.2]

array([0.36363636])

In [44]:
numpy.where(feature_importances > 0.2)

(array([21323], dtype=int64),)

In [47]:
print vectorizer.get_feature_names()[21323]

houectect


### What’s the accuracy of the decision tree now?

In [48]:
accuracy_score(labels_test, labels_pred)

0.8134243458475541